import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  atlasSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Products',
      items: [
        'products/overview',
        {
          type: 'category',
          label: 'Core',
          items: [
            'products/matches',
            'products/ragbaz-frog',
            'products/ragbaz-design-system',
            'products/typeset',
            {
              type: 'category',
              label: 'Articulate',
              items: [
                'products/articulate/overview',
                'products/articulate/scenario-secure-wp',
                'products/articulate/scenario-headless-commerce',
                'products/articulate/universe',
                'products/articulate/storefront',
                'products/articulate/universe-wp-cf-front-oss',
                'products/articulate/universe-ragbaz-xyz',
                'products/articulate/universe-multitenant-wp-mcp-docker-legacy',
                'products/articulate/universe-wp-proxy',
                'products/articulate/universe-wp-from-backup',
                'products/articulate/gatekeeper',
                'products/articulate/mailstack',
                'products/articulate/registry',
                'products/articulate/wp-ai',
                'products/articulate/wp-sidecar',
                'products/articulate/wp-wasi',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Active',
          items: [
            'products/detcordon',
            'products/shipwrecks-se',
            'products/mailroute',
            'products/chatwoot',
            'products/discord-bot',
          ],
        },
        'products/bazaar',
      ],
    },
    {
      type: 'category',
      label: 'Experiments',
      items: [
        'experiments/overview',
        {
          type: 'category',
          label: 'BAZ Platform',
          items: [
            'experiments/baz-architecture',
            'experiments/baz-hft',
            'experiments/baz-luna',
            'experiments/baz-palantir',
            'experiments/baz-cx',
          ],
        },
        'experiments/glither-wasm-wit-compiler-spec',
        'experiments/glither-mailguard-example',
        'experiments/glither-world-sketch',
        'experiments/dana-no-retrograde-sketch',
        'experiments/glither-governance',
        'experiments/eu-ai-act-compliance-plan',
        'experiments/glither-ast-visualization',
        'experiments/comet-trail',
        'experiments/omniland/overview',
        'experiments/omniland/my-editor',
        'experiments/omniland/omniland2',
        'experiments/react-google-font-chooser-ui',
        'experiments/phpvm',
        'experiments/tanstack-start-basic-cloudflare',
        'experiments/tanstack-supabase-start-basic',
        'experiments/aied',
        'experiments/slint',
        'experiments/esp32tolk',
      ],
    },
    {
      type: 'category',
      label: 'Drafts',
      items: [
        {type: 'link', label: 'Font Chooser', href: '/drafts/font-chooser'},
        {type: 'link', label: 'Theme Editor', href: '/drafts/theme-editor'},
        {type: 'link', label: 'Compose View', href: '/drafts/docker-compose-view'},
        {type: 'link', label: 'Audio Sink Bleep', href: '/drafts/spec-audio-sink'},
        {type: 'link', label: 'Phoneme Tauri App', href: '/drafts/spec-phoneme-app'},
        {type: 'link', label: 'WP GraphQL Bleep', href: '/drafts/spec-wp-graphql'},
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [
        'infra/overview',
        'infra/architecture',
        'infra/topology',
        'infra/debian-updater',
        'infra/dev-tooling',
        'infra/migrate',
        'infra/pub-pipe',
        'infra/traefik',
        'infra/haproxy',
        'infra/infisical',
        'infra/traefik-strapi',
      ],
    },
    {
      type: 'category',
      label: 'Private',
      items: [
        'private/overview',
        'private/kit-lkm-rootkit',
        'private/kit-php-runkit',
        'private/sec',
      ],
    },
    {
      type: 'category',
      label: 'Archive',
      items: [
        'archive/overview',
        'archive/detcordon-enforcement-prototype',
        'archive/storefront-xtas',
        'archive/portfolio',
        'archive/scipub',
      ],
    },
    {
      type: 'category',
      label: 'Vendor',
      items: [
        'vendor/overview',
        'vendor/claude-code',
        'vendor/yakpro-po',
        'vendor/headless',
      ],
    },
  ],
};

export default sidebars;
