services:
  doc-site:
    image: ${DOC_IMAGE:-doc-ragbaz-xyz:latest}
    container_name: doc-ragbaz-xyz-content
    restart: unless-stopped
    ports:
      - "127.0.0.1:8890:80"
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc-ragbaz-xyz.rule=Host(`doc.ragbaz.cc`) || Host(`www.doc.ragbaz.cc`)"
      - "traefik.http.routers.doc-ragbaz-xyz.tls=true"
      - "traefik.http.routers.doc-ragbaz-xyz.tls.certresolver=le-dns"
      - "traefik.http.services.doc-ragbaz-xyz.loadbalancer.server.port=80"

networks:
  traefik-public:
    name: traefik-public
    external: true
